version: '3'
services:
  starburger_postgres:
    image: postgres:latest
    container_name: starburger_postgres
    restart: always
    volumes:
      - .:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
  front:
    container_name: starburger-frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - .:/star-burger/staticfiles/
  back:
    container_name: starburger-backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - .:/star-burger/media/
      - .:/star-burger/staticfiles/
    command: >
      bash -c "gunicorn -w 5 -b 0.0.0.0:8080 star_burger.wsgi:application"
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - front
